name: Validar y Actualizar datos.json

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta una vez al d√≠a a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Descargar datos desde Google Sheets
        run: |
          curl -o datos.json "https://script.google.com/macros/s/AKfycbyFHz6BrnC4DKeDOYb3nW2mfoQpnSf-qaWirVPvCEreqsYQtGQg7A73IOYXMXLO6ZoL/exec"

      - name: Validar datos.json
        run: |
          sudo apt-get install -y jq
          jq empty datos.json

      - name: Commit y Push de cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add datos.json
          git commit -m "Actualizar datos.json [skip ci]" || echo "No hay cambios para commit"
          git push
